version: '3.9'

services:
  dbt:
    build:
      context: .
    container_name: dbt_bigquery
    volumes:
      - .:/app                   # Mount the project directory
      #- ./.dbt:/root/.dbt        # Mount the .dbt directory containing profiles.yml
    environment:
      DBT_PROFILES_DIR: /app/.dbt  # Specify the profiles.yml directory
    ports:
      - "8080:8080"              # Map port 8080 to serve docs
    stdin_open: true
    tty: true
    command: |
      sh -c "if [ -f /app/.dbt/cred.json ]; then \
        echo 'Cred file is present in /root/.dbt'; \
        else echo 'Error: cred.json not found in /root/.dbt'; \
      fi; tail -f /dev/null"