apiVersion: v1
kind: Service
metadata:
  name: dbt-docs-service
  namespace: default
spec:
  selector:
    app: dbt-docs-task
  ports:
    - protocol: TCP
      port: 8080  # External port
      targetPort: 8080  # Container port
  type: LoadBalancer  # Expose the service externally
