apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-pod-access
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view  # Grants view permissions to pods
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
