apiVersion: v1
kind: Service
metadata:
  name: dbt-deployement
  namespace: default
spec:
  selector:
    app: dbt-deployement
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
