name: Deploy DAG to Airflow
on:
  push:
    branches:
      - main
    paths:
      - "dags/**"

jobs:
  deploy-dag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Upload DAG to Composer
      run: |
        gsutil cp ./dags/dbt_pipeline_dag.py gs://bdm-project-bucket/dags/
