version: 2

models:
  - name: final_booking_analytics
    description: "Final analytics-ready table with booking metrics aggregated by year and month."
    columns:
      - name: hotel
        description: "The name of the hotel."
        data_tests:
          - not_null

      - name: arrival_date_year
        description: "Year of arrival for bookings."
        data_tests:
          - not_null
          - accepted_values:
              values: [2015, 2016, 2017]  
              
      - name: arrival_date_month
        description: "Month of arrival for bookings."
        data_tests:
          - not_null

      # - name: total_bookings
      #   description: "Total number of bookings aggregated by hotel, year, and month."
      #   data_tests:
      #     - not_null
      #     - greater_than: { value: 0 }

      # - name: revenue
      #   description: "Total revenue calculated as ADR * duration for non-canceled bookings."
      #   data_tests:
      #     - not_null
      #     - greater_than: { value: 0 }

      # - name: avg_lead_time
      #   description: "Average lead time for bookings."
      #   data_tests:
      #     - not_null
      #     - greater_than: { value: 0 }
