name: Deploy DAG to Airflow
on:
  push:
    branches:
      - master
    paths:
      - "dags/**"
      - ".github/workflows/airflow_deployment.yaml"

jobs:
  deploy-dag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    - name: List Files in Working Directory
      run: |
        echo "Current working directory:"
        pwd
        echo "Files and directories:"
        ls -R  # Lists files recursively
    - name: Upload DAG to Composer
      run: |
        gcloud storage cp ./dags/dbt_pipeline.py gs://asia-south1-bdm-project-sch-34306c64-bucket/dags
