name: Deploy Docker to GKE

on:
  push:
    branches:
      - master
    path:
      - "!dags/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3


    - name: Create a JSON file
      run: |
        echo "${{ secrets.JSON_FILE }}" > .dbt/cred.json
        
    - name: Check JSON file
      run: |
        cat .dbt/cred.json
    # Step 4: Debug file paths (optional)
    - name: Debug Files
      run: ls .dbt -A

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    # Step 3: Configure Docker for GCP
    - name: Configure Docker for GCP
      run: gcloud auth configure-docker

    # # Step 4: Build Docker image
    - name: Build Docker Image
      run: |
        docker build --build-arg GCP_SERVICE_ACCOUNT_KEY="temp/cred.json" -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/dbt_image:latest .

    # # Step 5: Push Docker image to Google Container Registry (GCR)
    - name: Push Docker Image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/dbt_image:latest

    - name: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: 'bdm-project'
        location: 'asia-south1'
    
    - name: 'deploy'
      shell: bash
      run: |
        kubectl apply -f k8s/deploy.yaml 
        kubectl rollout restart deployment dbt-deployement 
        kubectl get pods
        kubectl get deployment