name: Deploy Docker to GKE

on:
  push:
    branches:
      - master  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Create a JSON file
      run: |
        mkdir -p temp
        echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > temp/cred.json
      # Step 2: Authenticate with Google Cloud
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    # Step 3: Configure Docker for GCP
    - name: Configure Docker for GCP
      run: gcloud auth configure-docker

    # Step 4: Debug file paths (optional)
    - name: Debug Files
      run: ls -R

    # # Step 4: Build Docker image
    - name: Build Docker Image
      run: |
        docker build --build-arg GCP_SERVICE_ACCOUNT_KEY="temp/cred.json" -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/dbt_image:latest .

    # # Step 5: Push Docker image to Google Container Registry (GCR)
    - name: Push Docker Image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/dbt_image:latest

    - name: 'deploy with gke-deploy cli'
      uses: 'google-github-actions/deploy-gke-container@v0.1'
      with:
        image: 'dbt_image'
        app_name: ' dbt_pipeline'
        region: 'asia-south1'
        cluster_name: 'bdm-project'
        project_id: 'iitj-capstone-project-group-18'
        namespace: 'default'
        expose: '8000'
    
    - name: 'get-deployments'
      shell: bash
      run: |
        kubectl get pods -n my-namespace
        kubectl get deployment -n my-namespace