name: Deploy Docker to GKE

on:
  push:
    branches:
      - master  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # # Step 1: Checkout code
    # - name: Checkout Code
    #   uses: actions/checkout@v3
    - name: Create a JSON file
      run: |
        mkdir -p temp
        echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > temp/cred.json

    - name: 'Authenticating with Gcloud using SA'
      run: |
          gcloud auth login  --cred-file='temp/cred.json'
    - name: 'Setting SA Account as default'
      run: |
        gcloud config set account ACCOUNT
    - name: 'Setting Project ID'
      run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: 'Configuring Docker'
      run: |
        gcloud --quiet auth configure-docker

    # - name: 'Activating SA account'
    #   run: |
    #     gcloud auth activate-service-account ACCOUNT

    # - id: 'get-credentials'
    #   run: |
    #     gcloud container clusters get-credentials bdm-project --region asia-south1 --project iitj-capstone-project-group-18
      # uses: 'google-github-actions/get-gke-credentials@v2'
      # with:
      #   project_id: ${{ secrets.GCP_PROJECT_ID }}
      #   cluster_name: 'bdm-project'
      #   location: 'asia-south1'
        #credentials: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    # # Step 4: Build Docker image
    - name: Build Docker Image
      run: |
        docker build --build-arg GCP_SERVICE_ACCOUNT_KEY="${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/dbt_image:latest .

    # # Step 5: Push Docker image to Google Container Registry (GCR)
    - name: Push Docker Image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/dbt_image:latest

    # # Step 6: Deploy to GKE
    # - name: Deploy to GKE
    #   run: |
    #     kubectl apply -f k8s/deployment.yaml  # Replace with your Kubernetes deployment file path
    #     kubectl apply -f k8s/service.yaml     # Replace with your Kubernetes service file path

    # # Step 7: Verify deployment
    # - name: Verify Deployment
    #   run: |
    #     kubectl rollout status deployment/${{ secrets.K8S_DEPLOYMENT_NAME }}
